/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTagsIndexRouteImport } from './routes/_layout/tags/index'
import { Route as LayoutSign_inIndexRouteImport } from './routes/_layout/sign_in/index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTagsIndexRoute = LayoutTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSign_inIndexRoute = LayoutSign_inIndexRouteImport.update({
  id: '/sign_in/',
  path: '/sign_in/',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/sign_in/': typeof LayoutSign_inIndexRoute
  '/tags/': typeof LayoutTagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/sign_in': typeof LayoutSign_inIndexRoute
  '/tags': typeof LayoutTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/sign_in/': typeof LayoutSign_inIndexRoute
  '/_layout/tags/': typeof LayoutTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign_in/' | '/tags/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign_in' | '/tags'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/sign_in/'
    | '/_layout/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tags/': {
      id: '/_layout/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof LayoutTagsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sign_in/': {
      id: '/_layout/sign_in/'
      path: '/sign_in'
      fullPath: '/sign_in/'
      preLoaderRoute: typeof LayoutSign_inIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutSign_inIndexRoute: typeof LayoutSign_inIndexRoute
  LayoutTagsIndexRoute: typeof LayoutTagsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutSign_inIndexRoute: LayoutSign_inIndexRoute,
  LayoutTagsIndexRoute: LayoutTagsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
