/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SigninIndexImport } from './routes/sign_in/index'
import { Route as MemesIndexImport } from './routes/memes/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SigninIndexRoute = SigninIndexImport.update({
  id: '/sign_in/',
  path: '/sign_in/',
  getParentRoute: () => rootRoute,
} as any)

const MemesIndexRoute = MemesIndexImport.update({
  id: '/memes/',
  path: '/memes/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/memes/': {
      id: '/memes/'
      path: '/memes'
      fullPath: '/memes'
      preLoaderRoute: typeof MemesIndexImport
      parentRoute: typeof rootRoute
    }
    '/sign_in/': {
      id: '/sign_in/'
      path: '/sign_in'
      fullPath: '/sign_in'
      preLoaderRoute: typeof SigninIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/memes': typeof MemesIndexRoute
  '/sign_in': typeof SigninIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/memes': typeof MemesIndexRoute
  '/sign_in': typeof SigninIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/memes/': typeof MemesIndexRoute
  '/sign_in/': typeof SigninIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/memes' | '/sign_in'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/memes' | '/sign_in'
  id: '__root__' | '/' | '/memes/' | '/sign_in/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MemesIndexRoute: typeof MemesIndexRoute
  SigninIndexRoute: typeof SigninIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MemesIndexRoute: MemesIndexRoute,
  SigninIndexRoute: SigninIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/memes/",
        "/sign_in/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/memes/": {
      "filePath": "memes/index.tsx"
    },
    "/sign_in/": {
      "filePath": "sign_in/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
