/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as SigninIndexImport } from './routes/sign_in/index'
import { Route as LayoutTagsIndexImport } from './routes/_layout/tags/index'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SigninIndexRoute = SigninIndexImport.update({
  id: '/sign_in/',
  path: '/sign_in/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutTagsIndexRoute = LayoutTagsIndexImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/sign_in/': {
      id: '/sign_in/'
      path: '/sign_in'
      fullPath: '/sign_in'
      preLoaderRoute: typeof SigninIndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout/tags/': {
      id: '/_layout/tags/'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof LayoutTagsIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutTagsIndexRoute: typeof LayoutTagsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutTagsIndexRoute: LayoutTagsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/sign_in': typeof SigninIndexRoute
  '/tags': typeof LayoutTagsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/sign_in': typeof SigninIndexRoute
  '/tags': typeof LayoutTagsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/sign_in/': typeof SigninIndexRoute
  '/_layout/tags/': typeof LayoutTagsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/sign_in' | '/tags'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/sign_in' | '/tags'
  id: '__root__' | '/' | '/_layout' | '/sign_in/' | '/_layout/tags/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  SigninIndexRoute: typeof SigninIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  SigninIndexRoute: SigninIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/sign_in/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/tags/"
      ]
    },
    "/sign_in/": {
      "filePath": "sign_in/index.tsx"
    },
    "/_layout/tags/": {
      "filePath": "_layout/tags/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
