default:
    . .nix-profile/etc/profile.d/nix.sh && nix run home-manager switch

clean:
    . .nix-profile/etc/profile.d/nix.sh && nix-store --gc

install-nix:
    curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install | sh -s -- --no-daemon
